 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using Abp.Dependency;

namespace MyProject
{
    public class AppFolders : IAppFolders, ISingletonDependency
    {
        public string TempFileDownloadFolder { get; set; }
        public string DemoUploadFolder { get; set; }
        public string DemoFileDownloadFolder { get; set; }

    }
}