 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
namespace MyProject
{
    public interface IAppFolders
    {
        string TempFileDownloadFolder { get; }
        string DemoUploadFolder { get; }
        string DemoFileDownloadFolder { get; }

    }
}