 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;

namespace MyProject.Global
{
    public class GlobalConst
    {
        public enum TrangThaiThucThiQuery
        {
            ThanhCong = 1,
            ThatBai,
        }

        public enum ReadExcelResultCode
        {
            FileNotFound = 1,
            CantReadData,
            OK = 200
        }
    }
}
