 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;

namespace MyProject.Global
{
    public class GlobalModel
    {
        // Trạng thái Hiệu lực
        public static SortedList<int, string> SortedTrangThaiHieuLuc = new SortedList<int, string>
        {
            { 1, "Khởi tạo" },
            { 2, "Hiệu lực"},
            { 3, "Hết hiệu lực"},
        };

        // Trạng thái duyệt
        public static SortedList<int, string> SortedTrangThaiDuyet = new SortedList<int, string>
        {
            { 1, "Khởi tạo" },
            { 2, "Chờ duyệt"},
            { 3, "Đã duyệt"},
            { 4, "Không duyệt"},
        };

        public static SortedList<int, string> ReadExcelResultCode = new SortedList<int, string>
        {
            { 1   , "Có lỗi: Không tìm thấy file!" },
            { 2   , "Không đọc được dữ liệu, sai cấu trúc file hoặc dữ liệu rỗng!" },
            { 200 , "Thành công!" }
        };
    }
}
