 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using MyProject.Global.Dtos;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace MyProject.Global
{
    public interface ILookupTableAppService
    {
        Task<List<LookupTableDto>> GetAllTrangThaiHieuLuc();
        Task<List<LookupTableDto>> GetAllTrangThaiDuyet();
        Task<List<LookupTableDto>> GetAllDemo();
     }
}
