// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Abp.Authorization;
using Abp.Localization;
using Abp.MultiTenancy;

namespace MyProject.Authorization
{
     public class MyProjectAuthorizationProvider : AuthorizationProvider
     {
          public override void SetPermissions(IPermissionDefinitionContext context)
          {
               context.CreatePermission(PermissionNames.Pages_Users, L("Users"));
               context.CreatePermission(PermissionNames.Pages_Roles, L("Roles"));
               context.CreatePermission(PermissionNames.Pages_Demos, L("Demos"));
               context.CreatePermission(PermissionNames.Pages_Tenants, L("Tenants"), multiTenancySides: MultiTenancySides.Host);

               #region Danh mục
               var danhMuc = context.CreatePermission(PermissionNames.Pages_DanhMuc, L("DanhMuc"));
               danhMuc.CreateChildPermission(PermissionNames.Pages_DoiTac, L("DoiTac"));
               danhMuc.CreateChildPermission(PermissionNames.Pages_TinhThanh, L("TinhThanh"));
               danhMuc.CreateChildPermission(PermissionNames.Pages_QuanHuyen, L("QuanHuyen"));
               #endregion

               #region Quản lý chi phí
               var chiPhi = context.CreatePermission(PermissionNames.Pages_ChiPhi, L("ChiPhi"));
               chiPhi.CreateChildPermission(PermissionNames.Pages_CanhBaoChiPhi, L("CanhBaoChiPhi"));
               #endregion

               #region Quản lý hợp đồng
               var hopDong = context.CreatePermission(PermissionNames.Pages_HopDong, L("HopDong"));
               hopDong.CreateChildPermission(PermissionNames.Pages_HopDongTruyenDan, L("HopDongTruyenDan"));
               hopDong.CreateChildPermission(PermissionNames.Pages_BangGiaHopDongDungLuong, L("BangGiaHopDongDungLuong"));
               hopDong.CreateChildPermission(PermissionNames.Pages_HopDongCapQuang, L("HopDongCapQuang"));
               hopDong.CreateChildPermission(PermissionNames.Pages_HopDongInternet, L("HopDongInternet"));
               #endregion

               #region Kênh
               var kenh = context.CreatePermission(PermissionNames.Pages_QuanLyKenh, L("QuanLyKenh"));
               kenh.CreateChildPermission(PermissionNames.Pages_Kenh, L("Kenh"));
               kenh.CreateChildPermission(PermissionNames.Pages_HieuChinhKenhVaSuCo, L("HieuChinhKenhVaSuCo"));
               #endregion

               #region Đối soát
               var doiSoat = context.CreatePermission(PermissionNames.Pages_DoiSoat, L("DoiSoat"));
               doiSoat.CreateChildPermission(PermissionNames.Pages_DoiSoatChatLuongKenh, L("DoiSoatChatLuongKenh"));
               doiSoat.CreateChildPermission(PermissionNames.Pages_DoiSoatCuoc, L("DoiSoatCuoc"));
               #endregion

               #region Đề nghị thanh toán
               var deNghiThanhToan = context.CreatePermission(PermissionNames.Pages_QuanLyDeNghiThanhToan, L("QuanLyDeNghiThanhToan"));
               deNghiThanhToan.CreateChildPermission(PermissionNames.Pages_DeNghiThanhToan, L("DeNghiThanhToan"));
               #endregion

          }

          private static ILocalizableString L(string name)
          {
               return new LocalizableString(name, MyProjectConsts.LocalizationSourceName);
          }
     }
}
