// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
namespace MyProject.Authorization
{
     public static class PermissionNames
     {
          public const string Pages_Tenants = "Pages.Tenants";

          public const string Pages_Users = "Pages.Users";

          public const string Pages_Roles = "Pages.Roles";

          public const string Pages_Demos = "Pages.Demos";

          public const string Pages_DanhMuc = "Pages.DanhMuc";

          public const string Pages_DoiTac = "Pages.DoiTac";

          public const string Pages_TinhThanh = "Pages.TinhThanh";

          public const string Pages_QuanHuyen = "Pages.QuanHuyen";

          #region Quản lý chi phí
          public const string Pages_ChiPhi = "Pages.ChiPhi";
          public const string Pages_CanhBaoChiPhi = "Pages.CanhBaoChiPhi";
          #endregion

          #region Quản lý hợp đồng
          public const string Pages_HopDong = "Pages.HopDong";
          public const string Pages_HopDongTruyenDan = "Pages.HopDongTruyenDan";
          public const string Pages_BangGiaHopDongDungLuong = "Pages.BangGiaHopDongDungLuong";
          public const string Pages_HopDongCapQuang = "Pages.HopDongCapQuang";
          public const string Pages_HopDongInternet = "Pages.HopDongInternet";
          #endregion

          #region Kênh
          public const string Pages_QuanLyKenh = "Pages.QuanLyKenh";
          public const string Pages_Kenh = "Pages.Kenh";
          public const string Pages_HieuChinhKenhVaSuCo = "Pages.HieuChinhKenhVaSuCo";
          #endregion

          #region Đối soát
          public const string Pages_DoiSoat = "Pages.DoiSoat";
          public const string Pages_DoiSoatChatLuongKenh = "Pages.DoiSoatChatLuongKenh";
          public const string Pages_DoiSoatCuoc = "Pages.DoiSoatCuoc";
          #endregion

          #region Đề nghị thanh toán
          public const string Pages_QuanLyDeNghiThanhToan = "Pages.QuanLyDeNghiThanhToan";
          public const string Pages_DeNghiThanhToan = "Pages.DeNghiThanhToan";
          #endregion
     }
}
